# Generated by Django 4.1.3 on 2022-12-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quesion',
            new_name='question',
        ),
    ]
