# Generated by Django 4.1.3 on 2022-12-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_quesion_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='decription',
            new_name='description',
        ),
    ]
